name: Build Binaries

on:
  workflow_call:
    inputs:
      release_name:
        description: "allow setting the release name"
        default: "latest"
        required: false
        type: string

permissions:
  contents: write

jobs:
  publish:
    name: Publish
    if: always() && !cancelled()
    runs-on: ubuntu-latest

    steps:
      - name: Download binaries
        if: always() && !cancelled()
        uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4.3.0
        with:
          name: Firmware

      - name: Delete release
        run: gh release delete ${{ inputs.release_name || 'latest' }} --cleanup-tag || true
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Generate Release
        uses: softprops/action-gh-release@a06a81a03ee405af7f2048a818ed3f03bbf83c7b # v2.5.0
        if: always() && !cancelled()
        with:
          token: ${{ github.token }}
          name: Latest QMK Firmware
          tag_name: ${{ inputs.release_name || 'latest' }}
          fail_on_unmatched_files: false
          draft: false
          prerelease: false
          files: |
            **/*.hex
            **/*.bin
            **/*.uf2
